[2018-02-02 14:26:23] viennamoi.CRITICAL: InvalidArgumentException: The controller for URI "/bakery" is not callable. Expected method "getBakerysAction" on class "viennamoi\Controller\HomeController", did you mean "bakeryAction"? (uncaught exception) at C:\xampp\htdocs\viennamoi\vendor\symfony\http-kernel\Controller\ControllerResolver.php line 91 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/bakery\" is not callable. Expected method \"getBakerysAction\" on class \"viennamoi\\Controller\\HomeController\", did you mean \"bakeryAction\"? at C:\\xampp\\htdocs\\viennamoi\\vendor\\symfony\\http-kernel\\Controller\\ControllerResolver.php:91)"} []
[2018-02-02 14:27:42] viennamoi.CRITICAL: InvalidArgumentException: The controller for URI "/bakery" is not callable. Expected method "getBakeryAction" on class "viennamoi\Controller\HomeController", did you mean "bakeryAction"? (uncaught exception) at C:\xampp\htdocs\viennamoi\vendor\symfony\http-kernel\Controller\ControllerResolver.php line 91 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/bakery\" is not callable. Expected method \"getBakeryAction\" on class \"viennamoi\\Controller\\HomeController\", did you mean \"bakeryAction\"? at C:\\xampp\\htdocs\\viennamoi\\vendor\\symfony\\http-kernel\\Controller\\ControllerResolver.php:91)"} []
[2018-02-02 14:28:19] viennamoi.CRITICAL: InvalidArgumentException: The controller for URI "/bakery" is not callable. Expected method "getbakeryAction" on class "viennamoi\Controller\HomeController", did you mean "bakeryAction"? (uncaught exception) at C:\xampp\htdocs\viennamoi\vendor\symfony\http-kernel\Controller\ControllerResolver.php line 91 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/bakery\" is not callable. Expected method \"getbakeryAction\" on class \"viennamoi\\Controller\\HomeController\", did you mean \"bakeryAction\"? at C:\\xampp\\htdocs\\viennamoi\\vendor\\symfony\\http-kernel\\Controller\\ControllerResolver.php:91)"} []
[2018-02-02 14:28:35] viennamoi.ERROR: E_RECOVERABLE_ERROR: Object of class viennamoi\Domain\Address could not be converted to string {"code":4096,"message":"Object of class viennamoi\\Domain\\Address could not be converted to string","file":"C:\\xampp\\htdocs\\viennamoi\\vendor\\twig\\twig\\lib\\Twig\\Environment.php(467) : eval()'d code","line":70} []
[2018-02-02 14:28:35] viennamoi.CRITICAL: Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class viennamoi\Domain\Address could not be converted to string"). (uncaught exception) at C:\xampp\htdocs\viennamoi\views\bakery.html.twig line 20 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Catchable Fatal Error: Object of class viennamoi\\Domain\\Address could not be converted to string\"). at C:\\xampp\\htdocs\\viennamoi\\views\\bakery.html.twig:20, ErrorException(code: 0): Catchable Fatal Error: Object of class viennamoi\\Domain\\Address could not be converted to string at C:\\xampp\\htdocs\\viennamoi\\vendor\\twig\\twig\\lib\\Twig\\Environment.php(467) : eval()'d code:70)"} []
[2018-02-02 14:39:43] viennamoi.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'select * from products order by prod_id desc':  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'viennamoi.products' doesn't exist (uncaught exception) at C:\xampp\htdocs\viennamoi\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 57 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'select * from products order by prod_id desc':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'viennamoi.products' doesn't exist at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:57, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'viennamoi.products' doesn't exist at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:106, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'viennamoi.products' doesn't exist at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:104)"} []
[2018-02-02 15:21:20] viennamoi.ERROR: Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: Access Denied. (uncaught exception) at C:\xampp\htdocs\viennamoi\vendor\symfony\security\Http\Firewall\ExceptionListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\viennamoi\\vendor\\symfony\\security\\Http\\Firewall\\ExceptionListener.php:119, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\viennamoi\\vendor\\symfony\\security\\Http\\Firewall\\AccessListener.php:70)"} []
[2018-02-02 15:23:30] viennamoi.ERROR: Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: Access Denied. (uncaught exception) at C:\xampp\htdocs\viennamoi\vendor\symfony\security\Http\Firewall\ExceptionListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\viennamoi\\vendor\\symfony\\security\\Http\\Firewall\\ExceptionListener.php:119, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\viennamoi\\vendor\\symfony\\security\\Http\\Firewall\\AccessListener.php:70)"} []
[2018-02-02 15:23:55] viennamoi.CRITICAL: Pimple\Exception\UnknownIdentifierException: Identifier "dao.provider" is not defined. (uncaught exception) at C:\xampp\htdocs\viennamoi\vendor\pimple\pimple\src\Pimple\Container.php line 101 {"exception":"[object] (Pimple\\Exception\\UnknownIdentifierException(code: 0): Identifier \"dao.provider\" is not defined. at C:\\xampp\\htdocs\\viennamoi\\vendor\\pimple\\pimple\\src\\Pimple\\Container.php:101)"} []
[2018-02-02 15:31:38] viennamoi.ERROR: Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: Access Denied. (uncaught exception) at C:\xampp\htdocs\viennamoi\vendor\symfony\security\Http\Firewall\ExceptionListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\viennamoi\\vendor\\symfony\\security\\Http\\Firewall\\ExceptionListener.php:119, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\viennamoi\\vendor\\symfony\\security\\Http\\Firewall\\AccessListener.php:70)"} []
[2018-02-02 15:32:05] viennamoi.ERROR: Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: Access Denied. (uncaught exception) at C:\xampp\htdocs\viennamoi\vendor\symfony\security\Http\Firewall\ExceptionListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\viennamoi\\vendor\\symfony\\security\\Http\\Firewall\\ExceptionListener.php:119, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\viennamoi\\vendor\\symfony\\security\\Http\\Firewall\\AccessListener.php:70)"} []
[2018-02-02 15:32:22] viennamoi.ERROR: Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: Access Denied. (uncaught exception) at C:\xampp\htdocs\viennamoi\vendor\symfony\security\Http\Firewall\ExceptionListener.php line 119 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\viennamoi\\vendor\\symfony\\security\\Http\\Firewall\\ExceptionListener.php:119, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\viennamoi\\vendor\\symfony\\security\\Http\\Firewall\\AccessListener.php:70)"} []
[2018-02-02 15:53:29] viennamoi.ERROR: Uncaught Exception Error: "Call to a member function find() on null" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 109 {"exception":"[object] (Error(code: 0): Call to a member function find() on null at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:109)"} []
[2018-02-02 15:59:19] viennamoi.CRITICAL: ErrorException: Notice: Undefined property: viennamoi\DAO\UserDAO::$RoleDAO (uncaught exception) at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 109 {"exception":"[object] (ErrorException(code: 0): Notice: Undefined property: viennamoi\\DAO\\UserDAO::$RoleDAO at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:109)"} []
[2018-02-02 16:00:56] viennamoi.ERROR: Uncaught Exception Error: "Call to a member function find() on null" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 109 {"exception":"[object] (Error(code: 0): Call to a member function find() on null at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:109)"} []
[2018-02-02 16:01:24] viennamoi.ERROR: Uncaught Exception Error: "Call to a member function find() on null" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 109 {"exception":"[object] (Error(code: 0): Call to a member function find() on null at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:109)"} []
[2018-02-02 16:04:40] viennamoi.ERROR: Uncaught Exception Error: "Call to a member function find() on null" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 109 {"exception":"[object] (Error(code: 0): Call to a member function find() on null at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:109)"} []
[2018-02-02 16:11:53] viennamoi.ERROR: Uncaught Exception Error: "Call to undefined function viennamoi\DAO\vardump()" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 110 {"exception":"[object] (Error(code: 0): Call to undefined function viennamoi\\DAO\\vardump() at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:110)"} []
[2018-02-02 16:13:27] viennamoi.ERROR: Uncaught Exception Error: "Call to a member function find() on null" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 111 {"exception":"[object] (Error(code: 0): Call to a member function find() on null at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:111)"} []
[2018-02-02 16:16:36] viennamoi.ERROR: Uncaught Exception Error: "Call to a member function find() on null" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 111 {"exception":"[object] (Error(code: 0): Call to a member function find() on null at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:111)"} []
[2018-02-02 16:16:41] viennamoi.ERROR: Uncaught Exception Error: "Call to a member function find() on null" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 111 {"exception":"[object] (Error(code: 0): Call to a member function find() on null at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:111)"} []
[2018-02-02 16:22:33] viennamoi.ERROR: Uncaught Exception Error: "Call to a member function find() on null" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 111 {"exception":"[object] (Error(code: 0): Call to a member function find() on null at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:111)"} []
[2018-02-02 16:32:57] viennamoi.ERROR: Uncaught Exception Error: "Call to a member function find() on null" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 110 {"exception":"[object] (Error(code: 0): Call to a member function find() on null at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:110)"} []
[2018-02-02 16:40:01] viennamoi.ERROR: Uncaught Exception Error: "Call to a member function find() on null" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 110 {"exception":"[object] (Error(code: 0): Call to a member function find() on null at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:110)"} []
[2018-02-02 16:41:12] viennamoi.ERROR: Uncaught Exception Error: "Call to a member function find() on null" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 110 {"exception":"[object] (Error(code: 0): Call to a member function find() on null at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:110)"} []
[2018-02-02 16:44:21] viennamoi.ERROR: Uncaught Exception Error: "Call to a member function find() on null" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 110 {"exception":"[object] (Error(code: 0): Call to a member function find() on null at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:110)"} []
[2018-02-02 16:48:08] viennamoi.ERROR: Uncaught Exception Error: "Call to a member function find() on null" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 110 {"exception":"[object] (Error(code: 0): Call to a member function find() on null at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:110)"} []
[2018-02-02 16:49:16] viennamoi.ERROR: Uncaught Exception Error: "Call to a member function find() on null" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 110 {"exception":"[object] (Error(code: 0): Call to a member function find() on null at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:110)"} []
[2018-02-02 16:50:36] viennamoi.ERROR: Uncaught Exception Error: "Call to a member function find() on null" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 110 {"exception":"[object] (Error(code: 0): Call to a member function find() on null at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:110)"} []
[2018-02-02 16:56:19] viennamoi.ERROR: Uncaught Exception Error: "Call to undefined method viennamoi\Domain\User::getAdress()" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 64 {"exception":"[object] (Error(code: 0): Call to undefined method viennamoi\\Domain\\User::getAdress() at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:64)"} []
[2018-02-02 16:57:08] viennamoi.ERROR: Uncaught Exception Error: "Call to undefined method viennamoi\Domain\User::getAdress()" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 64 {"exception":"[object] (Error(code: 0): Call to undefined method viennamoi\\Domain\\User::getAdress() at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:64)"} []
[2018-02-02 16:57:58] viennamoi.ERROR: Uncaught Exception Error: "Call to undefined method viennamoi\Domain\User::getAdress()" at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 64 {"exception":"[object] (Error(code: 0): Call to undefined method viennamoi\\Domain\\User::getAdress() at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:64)"} []
[2018-02-02 16:59:14] viennamoi.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'INSERT INTO users (user_name, user_firstname, user_address, user_zipcode, user_city, user_tel, user_email, user_password, user_salt, user_role, fact_adress, fact_city, fact_zipcode) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["user", null, null, null, null, null, null, "$2y$13$YUIrdca5ZMQjaBI0HNXjUOEjHQ5knKE123LPRC1sdHUt6TyxjIilu", "f341e8570d2a40f0f3814ec", "ROLE_USER", null, null, null]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'viennamoi.users' doesn't exist (uncaught exception) at C:\xampp\htdocs\viennamoi\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 57 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'INSERT INTO users (user_name, user_firstname, user_address, user_zipcode, user_city, user_tel, user_email, user_password, user_salt, user_role, fact_adress, fact_city, fact_zipcode) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"user\", null, null, null, null, null, null, \"$2y$13$YUIrdca5ZMQjaBI0HNXjUOEjHQ5knKE123LPRC1sdHUt6TyxjIilu\", \"f341e8570d2a40f0f3814ec\", \"ROLE_USER\", null, null, null]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'viennamoi.users' doesn't exist at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:57, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'viennamoi.users' doesn't exist at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'viennamoi.users' doesn't exist at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2018-02-02 17:02:05] viennamoi.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'INSERT INTO vienn_user (user_name, user_firstname, user_address, user_zipcode, user_city, user_tel, user_email, user_password, user_salt, user_role, fact_adress, fact_city, fact_zipcode) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["user", null, null, null, null, null, null, "$2y$13$Aco2j85pv8mtW7h8NM.9reowZh8LdcNu\/YHiTWvwk1PPQWs9kHiPK", "9af59003fe3c7d3d86db132", "ROLE_USER", null, null, null]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'viennamoi.vienn_user' doesn't exist (uncaught exception) at C:\xampp\htdocs\viennamoi\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 57 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'INSERT INTO vienn_user (user_name, user_firstname, user_address, user_zipcode, user_city, user_tel, user_email, user_password, user_salt, user_role, fact_adress, fact_city, fact_zipcode) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"user\", null, null, null, null, null, null, \"$2y$13$Aco2j85pv8mtW7h8NM.9reowZh8LdcNu\\/YHiTWvwk1PPQWs9kHiPK\", \"9af59003fe3c7d3d86db132\", \"ROLE_USER\", null, null, null]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'viennamoi.vienn_user' doesn't exist at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:57, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'viennamoi.vienn_user' doesn't exist at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'viennamoi.vienn_user' doesn't exist at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2018-02-02 17:02:21] viennamoi.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'INSERT INTO vienn_user (user_name, user_firstname, user_address, user_zipcode, user_city, user_tel, user_email, user_password, user_salt, user_role, fact_adress, fact_city, fact_zipcode) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["user", null, null, null, null, null, null, "$2y$13$dldZkCtrZhm8XZ1gBnRIM.Vf\/DtmSjGqTPK33dHsfFz7gkYHoFZpq", "6d6275e70f14af2aa37bfe0", "ROLE_USER", null, null, null]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'viennamoi.vienn_user' doesn't exist (uncaught exception) at C:\xampp\htdocs\viennamoi\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 57 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'INSERT INTO vienn_user (user_name, user_firstname, user_address, user_zipcode, user_city, user_tel, user_email, user_password, user_salt, user_role, fact_adress, fact_city, fact_zipcode) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"user\", null, null, null, null, null, null, \"$2y$13$dldZkCtrZhm8XZ1gBnRIM.Vf\\/DtmSjGqTPK33dHsfFz7gkYHoFZpq\", \"6d6275e70f14af2aa37bfe0\", \"ROLE_USER\", null, null, null]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'viennamoi.vienn_user' doesn't exist at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:57, Doctrine\\DBAL\\Driver\\PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'viennamoi.vienn_user' doesn't exist at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S02): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'viennamoi.vienn_user' doesn't exist at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2018-02-02 17:03:27] viennamoi.CRITICAL: Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'INSERT INTO vienn_users (user_name, user_firstname, user_address, user_tel, user_email, user_password, user_salt, user_role) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params ["user", null, null, null, null, "$2y$13$3EwZlVeLrTuxA8mmCWo1XuL1ltwinGJXAqA2ug3qYH7VPYoNz.XLm", "bd389588858fb8af9d6f92d", "ROLE_USER"]:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_address' in 'field list' (uncaught exception) at C:\xampp\htdocs\viennamoi\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 75 {"exception":"[object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception occurred while executing 'INSERT INTO vienn_users (user_name, user_firstname, user_address, user_tel, user_email, user_password, user_salt, user_role) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [\"user\", null, null, null, null, \"$2y$13$3EwZlVeLrTuxA8mmCWo1XuL1ltwinGJXAqA2ug3qYH7VPYoNz.XLm\", \"bd389588858fb8af9d6f92d\", \"ROLE_USER\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_address' in 'field list' at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:75, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_address' in 'field list' at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_address' in 'field list' at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2018-02-02 17:05:03] viennamoi.CRITICAL: Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO vienn_users (user_name, user_firstname, user_tel, user_email, user_password, user_salt, user_role) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["user", null, null, null, "$2y$13$T2BXan41n.TlJRj9Iw8er.q7zC9Q7wqNw1z9c73X3A4VGhpHIWeg.", "7a4a84605f56a61f032cf20", "ROLE_USER"]:  SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_firstname' cannot be null (uncaught exception) at C:\xampp\htdocs\viennamoi\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 118 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO vienn_users (user_name, user_firstname, user_tel, user_email, user_password, user_salt, user_role) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [\"user\", null, null, null, \"$2y$13$T2BXan41n.TlJRj9Iw8er.q7zC9Q7wqNw1z9c73X3A4VGhpHIWeg.\", \"7a4a84605f56a61f032cf20\", \"ROLE_USER\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_firstname' cannot be null at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:118, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_firstname' cannot be null at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_firstname' cannot be null at C:\\xampp\\htdocs\\viennamoi\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2018-02-02 17:10:02] viennamoi.WARNING: Username could not be found in the selected user provider. {"username":null,"provider":"viennamoi\\DAO\\UserDAO"} []
[2018-02-02 17:10:11] viennamoi.CRITICAL: Exception: No user matching id 1 (uncaught exception) at C:\xampp\htdocs\viennamoi\src\DAO\UserDAO.php line 37 {"exception":"[object] (Exception(code: 0): No user matching id 1 at C:\\xampp\\htdocs\\viennamoi\\src\\DAO\\UserDAO.php:37)"} []
